language: go
go:
- 1.9.4
install:
- go get github.com/spf13/hugo
script: hugo -b http://vmvt.club
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: vmvt.club
  region: eu-west-2
  endpoint: vmvt.club.s3-website.eu-west-2.amazonaws.com
  local-dir: public
  skip_cleanup: true
  on:
    repo: rzimin/vmvt.club