baseURL = "/"
languageCode = "ru-RU"
title = "# Все можно в Тае"
theme = "kube"
description = "Проект #всеможновтае для тех, кому Таиланд милее всех на свете"
Paginate = 4
disqusShortname = "vmvt"

[Params]
  RSSLink = "/index.xml"
  author = "команда #всеможновтае"
  email = "team@vmvt.club"
  
[Params.seo.webmaster_verifications]
  yandex = "cd4a193dbb616362"

[[menu.main]]
    name = "Блог"
    weight = -100
    url = "/blog/"
